# Default page title
title: Infinispan

# Project id name
project: infinispan

# Project full name
project_name: Infinispan

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

asciidoctor:
  :attributes:
    icons: font
    sectanchors: true
    toclevels: 3
    numbered: true
    docinfo: ''
    source-highlighter: coderay
    backend: html5
    doctype: book    
    ## Leave this empty!!
    imagesdir: ''
    experimental: true
# Merge multiple JavaScript files to improve performance
fileMerger:
  enabled: true
  outputFilePath: /javascripts/infinispan.js
  paths:
    - /javascripts/ghembedder.min.js

# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 86400 # seconds
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - http://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static.jboss.org/theme/fonts/titilliumtext/
    - http://static.jboss.org/theme/fonts/font-awesome/
    - http://static.jboss.org/theme/images/common/
    - http://static.jboss.org/images/example/

# Update resource URLs based on the profile
profiles:
  development:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/3.2.0.2/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/3.2.0.2/bootstrap-community
  staging:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/3.2.0.2/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/3.2.0.2/bootstrap-community
    base_url: http://infinispan.github.io
  production:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/3.2.0.2/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/3.2.0.2/bootstrap-community
    base_url: http://infinispan.github.io
    analytics_account: UA-8601422-1
    deploy:
      host: github_pages
      branch: master
